### ISSUE TITLE
Crash/Timeout 270220

### ISSUE THREAD

**Issue by mrchristian** [akademie-oeffentliches-gesundheitswesen/Beta-System#2]
The Fidus Writer install 3.6 has been locking up in an infinite loop, the result is that users get a 502 or 504 error and the site is unreachable.

We have about 10 users and are working on 12 documents with 1 book.

The lock-up lasts somewhere between 30 minutes and an hour or more.

At some time the site functions again.

The system does not crash in terms of completely freezing up.

See error reports below.

Thanks

Simon

Websocket issue. Timeout . 

2020-02-27_17:16:59.84778 ERROR:tornado.application:Exception in callback functools.partial(<function wrap.<locals>.null_wrapper at 0x7f3f4140b950>, <Future finished exception=OSError(0, 'Error')>)
2020-02-27_17:16:59.84780 Traceback (most recent call last):
2020-02-27_17:16:59.84780   File "/home/fidus/venv/lib/python3.6/site-packages/tornado/ioloop.py", line 758, in _run_callback
2020-02-27_17:16:59.84781     ret = callback()
2020-02-27_17:16:59.84781   File "/home/fidus/venv/lib/python3.6/site-packages/tornado/stack_context.py", line 300, in null_wrapper
2020-02-27_17:16:59.84782     return fn(*args, **kwargs)
2020-02-27_17:16:59.84782   File "/home/fidus/venv/lib/python3.6/site-packages/tornado/ioloop.py", line 779, in _discard_future_result
2020-02-27_17:16:59.84783     future.result()
2020-02-27_17:16:59.84783   File "/home/fidus/venv/lib/python3.6/site-packages/tornado/gen.py", line 1141, in run
2020-02-27_17:16:59.84783     yielded = self

**Comment by mrchristian** [comment]
> 502 Bad Gateway
> nginx
> 
> Yesterday it was
> 
> 504 Bad Gateway
> nginx
> 

stuck in loop reading and writing media files

cpu pegged :

   340 fidus     20   0 1056220 572948  13640 R 87.5 14.0 345:25.35 
python

87.5%

eg


> The people at the book
> sprintstat("/home/fidus/fiduswriter/media/avatars/simon/resized/80/sim
> on_worthington.jpg", {st_mode=S_IFREG|0644, st_size=2260, ...}) = 0
sendto(40,
"\27\3\2\2\20[\v\330n\10\370\332\231\222\232cF1\341\336s\362\337\371\25M\321(_\217\343\265"...,
533, 0, NULL, 0) = 533
ioctl(40, FIONREAD, [0])                = 0
recvfrom(40,
"\27\3\2@0\261\301\\\32\10\250\263k\222\350\323\363\273\35\3\325N\245\222\23\206\334\225\230\222\263x"...,
64, 0, NULL, NULL) = 64
ioctl(40, FIONREAD, [16373])            = 0
recvfrom(40,
"\212\5X\276\205\33\353\343\6\r(\6\7\212\253\3215\361\33\t\203?\331\277\363\253\34\233Y\177\t\334"...,
16373, 0, NULL, NULL) = 16373
ioctl(40, FIONREAD, [49311])            = 0
recvfrom(40,
"\27\3\2@0nAF\207/`\257\366y\30\201\243\20\340\31G<\260\266\276\23\\QD\204.\26"...,
49311, 0, NULL, NULL) = 49311
ioctl(40, FIONREAD, [15317])            = 0
recvfrom(40,
"\27\3\2;\320&\t\207\275\374\235\342:A\264T%\256M\265\23@\20lHD\\o\330\373&\336"...,
15317, 0, NULL, NULL) = 15317
sendto(40,
"\27\3\2\1p|\375:\30^~\241\205z\320t\366\336\210f\274\200\0252F\300\202\233(\321X\21"...,
373, 0, NULL, 0) = 373
ioctl(40, FIONREAD, [0])                = 0
recvfrom(40,
"\27\3\2\3\340\241\270\370\202\21\253~e$\362\332\264\216/\3639\357?i6\246u\370
R9\211"..., 64, 0, NULL, NULL) = 64
ioctl(40, FIONREAD, [933])              = 0
recvfrom(40,
"_;\373/\357\34&\253e\0037XST\316f\270Ev\31\302\243\246\335\337\27IH\231\31\5H"...,
933, 0, NULL, NULL) = 933
sendto(40,
"\27\3\2\1P\256@9\24\332_\17Y\253\261\270/\17G\241c\333\361\260\32\214m\2\224\300\300\f"...,
341, 0, NULL, 0) = 341
ioctl(40, FIONREAD, [0])                = 0
recvfrom(40,
"\27\3\2\1\360\276\25O\236\250\211\232\233\216\\\272J\2304\356P\37\367:+f\33021\343)\221"...,
64, 0, NULL, NULL) = 64
ioctl(40, FIONREAD, [437])              = 0
recvfrom(40,
"]\320.\275D\367\236g\326\222\222T\344]\337.\337v(|>\245\250\201C\200G\3737\277\275\230"...,
437, 0, NULL, NULL) = 437
stat("/home/fidus/fiduswriter/media/avatars/jakob.schumacher/resized/80/profil.jpg",
{st_mode=S_IFREG|0644, st_size=2635, ...}) = 0 sendto(40, "\27\3\2\2\20\352g\242+\205\270\\\324\363?\273+\277\200!\320\202\212\n\314\232\266\377\255\371*\344"...,
533, 0, NULL, 0) = 533
ioctl(40, FIONREAD, [0])                = 0
recvfrom(40,
"\27\3\2@0\274\264\232[@\315\204\231d[\250\357`\355c\367(\255i\262%\25`@E6B"...,
64, 0, NULL, NULL) = 64
ioctl(40, FIONREAD, [16373])            = 0
recvfrom(40, "\366\2060hC\360\1\354
\267u\32S\265\307\265\205\364[Z\300\16\227\333f\212o\307\334\266\302R"...,
16373, 0, NULL, NULL) = 16373
ioctl(40, FIONREAD, [49311])            = 0
recvfrom(40,
"\27\3\2@0\177\2745|6\316N\232\3\210\371\273\242M\331\312'U\336\10\20#\377u\234c\0"...,
49311, 0, NULL, NULL) = 49311
ioctl(40, FIONREAD, [15317])            = 0
recvfrom(40,
"\27\3\2;\3203\323\366\223\267\r\220\207\23L0V\30Nj\17\340W4\3203\17\364_q\365\261"...,
15317, 0, NULL, NULL) = 15317
sendto(40,
"\27\3\2\1p\214\345/o\242\207t(\214U-C\226^\202k\336\2\261\305\346\316\233\315\344\21<"...,
373, 0, NULL, 0) = 373
ioctl(40, FIONREAD, [0])                = 0
recvfrom(40,
"\27\3\2\3\300\265\326\207\331\234m\266t\3536\226\246\221+\271\214\216\221J\337\204\33\256\213\376e\202"...,
64, 0, NULL, NULL) = 64
ioctl(40, FIONREAD, [901])              = 0
recvfrom(40,
"\"~o\207S\300\300D\30\17\336\322\202\373\373?\206\360YM/fh%\245\316\5\6$d+\300"...,
901, 0, NULL, NULL) = 901
sendto(40,
"\27\3\2\1P\230\216\354\205{\261\304\201I\331utf\364\367\322:1\5$\232\347\"\37266\337"...,
341, 0, NULL, 0) = 341
ioctl(40, FIONREAD, [0])                = 0
recvfrom(40,
"\27\3\2\1\240I\377\222|X\6+\246W\372)\234\247y^C\353\317\314@\376m\271%h\214\263"...,
64, 0, NULL, NULL) = 64
ioctl(40, FIONREAD, [357])              = 0
recvfrom(40,
"\275\21\373o\324(1\333\364c#\215)\23\204|\371\35#E\211\343&\25\4$\nWSk\357\270"...,
357, 0, NULL, NULL) = 357
sendto(40,
"\27\3\2\2\20\302z\366\330{{x-G\277\2348p\347'\252\3\365\\\37\277\23\315\342G\333\275"...,
533, 0, NULL, 0) = 533
ioctl(40, FIONREAD, [0])                = 0
recvfrom(40,
"\27\3\2@0\201&\300r\233\351\310\203O\33\215\233M1\233$\223\274k\275\2142\346.\37K\346"...,
64, 0, NULL, NULL) = 64
ioctl(40, FIONREAD, [16373])            = 0
recvfrom(40,
"\364\267\3674\31\334\263\236\34\3319\34\222\373OG\377\245>`\\E\300\323f\355\17\v\33\27(\224"...,
16373, 0, NULL, NULL) = 16373
ioctl(40, FIONREAD, [49311])            = 0
recvfrom(40,
"\27\3\2@0\333\323\245]\325\302\303;s=\251\343\335\\3\373\366\317\316A!e;>D\215\34"...,
49311, 0, NULL, NULL) = 49311
ioctl(40, FIONREAD, [15317])            = 0
recvfrom(40,
"\27\3\2;\320\26\31\203Y\302J\242(/]\372k\2\320\346y\306\276\231G4\25q;\37\275\210"...,
15317, 0, NULL, NULL) = 15317
sendto(40,
"\27\3\2\1p\262\256/bK\17td}g\244\35Shq\363\373y\20T\223\212d\226\372\253\376"...,
373, 0, NULL, 0) = 373
ioctl(40, FIONREAD, [0])                = 0
recvfrom(40,
"\27\3\2\3\320\3420E\311\0216\t<ys\36\360>\361C\342\324\r\311\25Eqp\330TO%"...,
64, 0, NULL, NULL) = 64
ioctl(40, FIONREAD, [917])              = 0
recvfrom(40,
"c\246\36499~Q\345J\374\26\350\267\352\230\254\240\362\177\370\244[*j\356\254\32\212t\266\366\276"...,
917, 0, NULL, NULL) = 917
sendto(40,
"\27\3\2\1PK\300\2073\23\327\303\374\23\227\244\254\3\356\22)\1t\375\255Un\2072[\231W"...,
341, 0, NULL, 0) = 341
ioctl(40, FIONREAD, [0])                = 0
recvfrom(40,
"\27\3\2\1\360\220\202\317-\353\210\252P|\343\265\205\265G\3231?\242\274\366\377z\2\261\226\350\355"...,
64, 0, NULL, NULL) = 64
ioctl(40, FIONREAD, [437])              = 0
recvfrom(40,
"\241W\2667\260V*z\211\244\230eF\250lQ\362/#U\312\305\314(n\2221+\206\317\35\27"...,
437, 0, NULL, NULL) = 437
^Cstrace: Process 340 detached

**Comment by mrchristian** [comment]
The lockup happen three days on the row - with 10 users on the system at one location.

Attempts have been made to replicate the lockup, but it has not been possible to replicate the problem.

10 test users were generated and adding to sprint users a total of 17 users were active on one document. Multiple actions were made at the same time: edits, downloads of all books, refreshing the document on multiple computers, and more. The system did not lockup.

So far unable to replicate the lockup.

The problem might have been a broken avatar image, as this was repaired. But a further attempt was made to replicate the broken avatar. This was done by closing browser during the avatar upload, which did break the avatar and give the result of the UI showing a broken image and using the user name alt tag.

This still did not lockup the system. 10 users were added to a document and again refreshing, stress testing the system was tried. The system did not lockup.

**Comment by mrchristian** [comment]
Since the problem cannot be replicated other approaches will be need to establish what has caused the bug.
